services:
  freshdesk-api-client:
    container_name: freshdesk-api
    image: pbranestrategy/freshdesk-api-client:0.1.2
    environment:
      - FD_API_KEY=<your api key>
      - FD_BASE_URI=https://<your freshdesk host>/api/v2
      - FD_CUSTOMER_NAME=<your freshdesk customer name>
      - FD_RMA_CASE_ID_PREFIX="<your RMA Case Custom Object Prefix>:_3-"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    profiles:
      - production
      - test
      - development

networks:
  backend:
    driver: bridge
